wip/app

lib/handle-pull-request-change.js
I was showing this app as an example to an integrator at Universe and noticed you can save yourself some regexes.
=> Minior refactoring

index.js
=> Set status when commits updated

lib/handle-pull-request-change.js
Closes #19
Works well with branch protection (https://github.com/wojtekmach/wip-bot/pull/1):
=> Change status 'error' to 'pending'

scripts/deploy.sh
=> deploy with latest now-cli version

lib/handle-pull-request-change.js
Ref - https://github.com/gr2m/wip-bot/pull/32/files#r167938732
=> Use of template literals

index.js, lib/handle-pull-request-change.js
=> refactor: remove unused robot param

package.json, scripts/deploy.sh
closes #42 (I don’t yet know what the problem was, but that fixes it)
=> Downgrade probot to 4.0.0

README.md
we don’t mention that commit messages work, too
=> README: usage clarifications

index.js
=> Listen for pull_request.(un)labeled

README.md, lib/handle-pull-request-change.js
=> Support "work in progress" label

PRIVACY_POLICY.md, README.md
I’ve no idea what I’m doing. This is generated using https://app-privacy-policy-generator.firebaseapp.com/# and adjusted to my best knowledge.
Just like the code I’d like this to be a great template for other developers of GitHub Apps. I’d very much appreciate any help
closes #70
=> privacy policy

lib/handle-pull-request-change.js, test/unit/lib/handle-pull-request-change.test.js
=> Get labels from webhook payload

lib/handle-pull-request-change.js, test/unit/lib/handle-pull-request-change.test.js
=> log events for private repositories

lib/handle-pull-request-change.js, test/unit/lib/handle-pull-request-change.test.js
=> Don’t set status unless changed

.env.example, index.js, lib/handle-pull-request-change.js, lib/send-logs.js, package.json, test/unit/lib/handle-pull-request-change.test.js
this also adds logging to logdna.com
=> structured logging

now.json, package.json
I already installed the app, now creating the required now.json
=> enable now app

now.json
This PR will deploy the app to wip.now.sh
closes #53
closes #96
closes #102
=> End marketplace beta preview

index.js, lib/handle-marketplace-purchase.js, now.json, test/integration/events/cancellation.json, test/integration/events/downgrade.json, test/integration/events/purchase-enterprise.json, test/integration/events/purchase.json, test/integration/events/upgrade.json, test/integration/marketplace-purchase-test.js
last second production change, what could go wrong lol
=> log marketplace_purchase events

pro-plan-for-free.js
Hey,
I'm a high school student, and I create some tools to better aid volunteer groups and teams (for example, the Trap Nation Community Moderation team and the Spotify Rock Star Program as well as a charity) in achieving the best for the people they serve.
I'd really appreciate being able to have the Pro features for Free with WIP app - it's really crucial to my Git flow 🙂
=> Adding myself for Pro for Free

now.json
disable stats as recommended by probot with a lot of installations: https://probot.github.io/docs/configuration/
=> disable stats

index.js, lib/logs/memory-usage.js
I want to make sure there is no memory leak somewhere in WIP. This is a follow up to #145
=> Log memory on 10s interval

README.md, lib/pro/default-config.js, lib/pro/get-config.js, lib/pro/get-status.js, lib/pro/set-status.js, package.json, test/integration/pro-plan-test.js
=> load configuration from .github repository

README.md, lib/pro/default-config.js, lib/pro/get-config.js, lib/pro/get-status.js, lib/pro/set-status.js, package.json, test/integration/pro-plan-test.js
Ooopsie.
This PR includes commits from #153
=> Remove #tbd links

lib/logs/get-child.js, lib/pro/get-config.js, lib/pro/get-status.js, lib/pro/set-status.js, test/integration/free-plan-test.js, test/integration/pro-plan-test.js
Curious how many folks use the configuration feature :)
=> log "hasConfig"

pro-plan-for-free.js
walking the talk 🛣️and subscribing for a paid account for WIP!
=> Removing myself from "Pro for Free" - list :)

lib/handle-pull-request-change.js, lib/logs/get-child.js, test/integration/free-plan-test.js, test/integration/pro-plan-test.js
=> Log durations

.gitignore, now.json, package-lock.json, package.json
using REDIS as backend, introduced in latest Probot beta:
https://github.com/probot/probot/blob/beta/docs/configuration.md
[![image](https://user-images.githubusercontent.com/39992/51791229-8989f500-2154-11e9-9e01-c43d59bdf56d.png)](https://github.com/probot/probot/blob/beta/docs/configuration.md)
=> Cluster support for request throttle caching

package-lock.json, package.json
via https://github.com/probot/probot/pull/836
=> Only use 2 redis connections instead of 8

lib/pro/set-status.js, package-lock.json, package.json, test/integration/pro-plan-test.js
This PR fixes the bug found where when a match is found in a label, the status would be:
`Title contains {match}` rather than `Label contains {match}`.
Purposed Changes: 
- Updated existing test to include check for title
- Update the title to include the location of where the match was found
closes #173
=> Fix: Status "In progress — Title contains" when a label is matched

package-lock.json, package.json
=> Update probot to the latest version 🚀

app.yml
Re: https://github.com/probot/twitter/pull/7 only thing I don't know is where to put the permission for the `.github/wip.yml`
=> Adding app.yml to help configure permissions automatically

HOW_IT_WORKS.md, index.js, lib/common/reset-repositories.js, lib/free/set-status.js, lib/handle-installation.js, lib/handle-pull-request-change.js, lib/pro/set-status.js, package-lock.json, package.json, test/integration/events/cancellation.json, test/integration/events/downgrade.json, test/integration/events/install.json, test/integration/events/new-permissions-accepted.json, test/integration/events/purchase-enterprise.json, test/integration/events/purchase.json, test/integration/events/repositories-added.json, test/integration/events/repositories-removed.json, test/integration/events/uninstall.json, test/integration/events/upgrade.json, test/integration/free-plan-test.js, test/integration/installation-test.js, test/integration/marketplace-purchase-test.js, test/integration/pro-plan-test.js
=> Update existing pull requests on install / permission change

lib/handle-pull-request-change.js
- `Erro code 403` --> `Error code 403`
=> Fix minor comment typo

pro-plan-for-free.js
closes https://github.com/wip/app/issues/219
=> Add Apache Organization to pro-plan-for-free.js

pro-plan-for-free.js
Hi!
I used to use the old username `itspugle`, but changed it to my current one, @timrossback, about a month or so ago. Anyways, I don't need the pro features anymore and have taken a bit of a step back from the volunteer platform I was developing, so I don't think I need to be listed anymore.
Thank you for 'gifting' free Pro to me 😄 
Cheers!
=> Removing my old username

lib/get-plan.js, lib/pro/set-status.js
addresses https://github.com/wip/app/issues/265#issuecomment-732153910
=> fix: login comparison for "pro-for-free" login entries

api/index.js, package-lock.json, package.json, public/stats/index.html
=> feat: redirect `GET /` to `GET /stats`

pro-plan-for-free.js
I added myself and my "org" that holds my projects and 2 other people, 1 of them was an alt account I no longer have access to 😭, while the other is for CI purposes to update submodules.
=> Added myself and my org that I mostly use that are free and open source.

package-lock.json, package.json
Update Probot to v12 beta. See https://github.com/probot/probot/pull/1559
=> fix: `probot@^12.0.0-beta.1`

pro-plan-for-free.js
We were a paying customer but now GH says we can't buy due to being invoiced. See https://github.com/wip/app/issues/498
Fixes #498
=> Add puppetlabs to free list

package-lock.json, package.json
/cc https://github.com/nock/nock/issues/2397
=> test: update to latest nock@beta

package.json, test/integration/free-plan-test.js, test/integration/installation-test.js, test/integration/marketplace-purchase-test.js, test/integration/pro-plan-test.js
see https://github.com/probot/probot/issues/1972#issuecomment-1937099785
=> test: remove `--timeout` and fix disabling throttling

api/index.js, package-lock.json, package.json, test/integration/free-plan-test.js
- Revert "fix(deps): update probot to v13 (#631)"
- Revert "test: update to latest nock@beta (#655)"
see https://github.com/probot/probot/issues/1973
=> fix: revert to probot v12

api/index.js, api/package.json, package-lock.json, package.json, test/integration/free-plan-test.js
see https://github.com/probot/probot/issues/1973#issuecomment-1937111521 thanks @wolfy1339
=> fix: bump to latest probot again

api/index.js, package-lock.json, package.json, test/integration/free-plan-test.js
This reverts commit cdba9f77fe0cfa5940ebed1e4a1aba84f2b672a0.
This should fix https://github.com/wip/app/issues/660
=> fix: revert to Probot v12 again

package-lock.json, package.json
=> fix: revert probot upgrade

lib/handle-installation.js, package-lock.json, package.json
- **refactor: remove `pluralize` package, use native `Intl` API instead**
- **build(package): lock file**
=> refactor: remove `pluralize` package, use native `Intl` API instead

api/index.js, package-lock.json, package.json, public/stats/index.html
=> feat: upgrade `probot` to v13
